# Generated by Django 3.1.1 on 2020-11-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0002_remove_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
    ]
