# Generated by Django 3.1.1 on 2020-11-30 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0004_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imdbNumber',
            new_name='netflixId',
        ),
    ]
